### ISSUE TITLE
大佬您好，请问下 Dcat Admin  ·  v2.0.13-beta 报这个错

### ISSUE THREAD

**Issue by bfsz** [sonhineboy/dcatadminlogincaptcha#1]
Problem 1
    - Conclusion: remove guzzlehttp/guzzle 7.2.0
    - Conclusion: don't install guzzlehttp/guzzle 7.2.0
    - sonhineboy/dcatadminlogincaptcha 1.0.2 requires guzzlehttp/guzzle ~6.5 -> satisfiable by guzzlehttp/guzzle[6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5, 6.5.x-dev].
    - sonhineboy/dcatadminlogincaptcha v1.0.0 requires guzzlehttp/guzzle ~6.5 -> satisfiable by guzzlehttp/guzzle[6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5, 6.5.x-dev].
    - sonhineboy/dcatadminlogincaptcha v1.0.1 requires guzzlehttp/guzzle ~6.5 -> satisfiable by guzzlehttp/guzzle[6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.0, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.1, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.2, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.3, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.4, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.5, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.2.0].
    - Installation request for guzzlehttp/guzzle (locked at 7.2.0, required as ^6.3.1|^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.2.0].
    - Installation request for sonhineboy/dcatadminlogincaptcha ^1.0 -> satisfiable by sonhineboy/dcatadminlogincaptcha[1.0.2, v1.0.0, v1.0.1].

需要将 guzzle 7.2.0 改成 6.5* 的版本吗？

**Comment by sonhineboy** [comment]
这个提示是  guzzlehttp/guzzle  这个扩展的版本太高了，
Problem 1
- Conclusion: remove guzzlehttp/guzzle 7.2.0
- Conclusion: don't install guzzlehttp/guzzle 7.2.0
先移除，再安装sonhineboy/dcatadminlogincaptcha 这个扩展
