### ISSUE TITLE
composer 安装该扩展失败显示与 guzzlehttp/guzzle 包版本不兼容

### ISSUE THREAD

**Issue by Z-hu** [sonhineboy/dcatadminlogincaptcha#2]
Using version ^1.0 for sonhineboy/dcatadminlogincaptcha
./composer.json has been updated
Running composer update sonhineboy/dcatadminlogincaptcha
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - sonhineboy/dcatadminlogincaptcha[v1.0.0, ..., 1.0.2] require guzzlehttp/guzzle ~6.5 -> found guzzlehttp/guzzle[6.5.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).
    - Root composer.json requires sonhineboy/dcatadminlogincaptcha ^1.0 -> satisfiable by sonhineboy/dcatadminlogincaptcha[v1.0.0, v1.0.1, 1.0.2].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by sonhineboy** [comment]
把你的 composer.lock 文件先删除，然后再安装这个包
