### ISSUE TITLE
composer require sonhineboy/dcatadminlogincaptcha 报错

### ISSUE THREAD

**Issue by andyzu** [sonhineboy/dcatadminlogincaptcha#3]
Using version ^1.0 for sonhineboy/dcatadminlogincaptcha
./composer.json has been updated
Running composer update sonhineboy/dcatadminlogincaptcha
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - spatie/eloquent-sortable 4.0.0 requires php ^8.0 -> your php version (7.3.9) does not satisfy that requirement.
    - dcat/laravel-admin 2.1.2-beta requires spatie/eloquent-sortable 3.*|4.* -> satisfiable by spatie/eloquent-sortable[4.0.0].
    - dcat/laravel-admin is locked to version 2.1.2-beta and an update of this package was not requested.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by sonhineboy** [comment]
这个是依赖问题
